services:
  fastapi:
    container_name: fastapi-api
    image: lasr2/authapi:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: "${SECRET_KEY:-suaChaveSecreta}"
    restart: always


  db:
    image: postgres:17
    container_name: postgres-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
      POSTGRES_DB: ${POSTGRES_DB:-projeto}